### ISSUE TITLE
[META] Should ExtensionDiscovery be converted over to a service?

### ISSUE THREAD

**Issue by ghost** [mrjmd/component_api#2]
Tagging in @balsama and @mrjmd for discussion.

**Pros:**
Possibly make it easier to allow other modules to provide component libraries?

**Cons:**
Plugin is currently simple and easy to understand.

**Comment by phenaproxima** [comment]
I'm thinking we should put something like this in the PDB core:

``` php
function pdb_library_info_build() {
  $libraries = array();

  $components = \Drupal::service('component_discovery')->getAllComponents();
  foreach ($components as $component) {
    if (isset($component['libraries'])) {
      $libraries = array_merge($libraries, $component['libraries']);
    }
  }

  return $libraries;
}
```

**Comment by ghost** [comment]
ExtensionDiscovery service was removed.
